Refactored code
Vendicated/powercord-brainfuck pull request #2
Opened 2021-03-24 04:05 UTC by X1nto

2021-03-25 05:19 UTC, Vendicated requested changes

2021-03-25 05:19 UTC, Vendicated commented on index.js
> +			this.errorlog(err);;
why is there two semis

2021-03-25 10:47 UTC, X1nto commented on index.js
> +			this.errorlog(err);;
oops

2021-03-25 14:22 UTC, Vendicated approved these changes

2021-04-29 19:18 UTC, Vendicated commented
superseded by https://github.com/Vendicated/powercord-brainfuck/commit/d1e309ac043970908707796a9836bb96a1dd0bee

2021-04-29 19:18 UTC, closed without merging

2021-04-29 20:41 UTC, X1nto commented
btch you could merge it 1 month ago

2021-04-29 20:53 UTC, Vendicated commented
HOSE MAD HOSE MAD 🇰🇵